### ISSUE TITLE
3x3 matrix for which SNF seems to fail (hangs and never completes)

### ISSUE THREAD

**Issue by glwhart** [brainandforce/NormalForms.jl#13]
```julia
3×3 Matrix{Int64}:
 2  0  0
 1  4  0
 2  0  8
```

I'm guessing that overflow or something is occurring, but I'm not sure. Not sure how to get debug information...

I tried the same matrix using the SNFer in this package that you referenced (https://github.com/wildart/SmithNormalForm.jl) and it worked fine. Found the SNF in just a blink.

**Comment by brainandforce** [comment]
The SNF calculations are actually done by adapting the algorithms from [HermiteNormalForm.jl](https://github.com/YingboMa/HermiteNormalForm.jl), and I'm going to admit that I have no formal background in linear algebra: I just needed that functionality for [Electrum.jl](https://github.com/brainandforce/Electrum.jl) and thought it would be best to offer it as a separate package.

I can have a look but I'm not sure what the timetable would be for pushing a fix.

**Comment by brainandforce** [comment]
It looks like the issue was that the code for zeroing out rows and columns during the Smith Normal Form was insufficiently robust. #14 should fix this.

**Comment by glwhart** [comment]
Thanks for taking a look at this. In one of my codes, I generate all possible HNF matrices of a given determinant size. Then I need the SNF and its left transform for some other calculation. So I end up testing your SNF routine with long lists of 3x3 matrices. This is the latest one I have found that exposes a bug in `snf`:

```
julia> t[:,:,1204]
3×3 Matrix{Int64}:
 1  0  0
 0  6  0
 0  3  4

julia> NormalForms.snf(t[:,:,1204])
ERROR: AssertionError: is_row_zero_after(A, k)
Stacktrace:
 [1] zero_row_and_col!(A::Matrix{Int64}, U::Matrix{Int64}, V::Matrix{Int64}, k::Int64, ki::Int64)
   @ NormalForms ~/.julia/packages/NormalForms/pD4Sx/src/algorithms.jl:287
 [2] snf_ma!(A::Matrix{Int64})
   @ NormalForms ~/.julia/packages/NormalForms/pD4Sx/src/smith.jl:98
 [3] snf!
   @ ~/.julia/packages/NormalForms/pD4Sx/src/smith.jl:115 [inlined]
 [4] snf(M::Matrix{Int64})
   @ NormalForms ~/.julia/packages/NormalForms/pD4Sx/src/smith.jl:122
 [5] top-level scope
   @ REPL[27]:1
```

**Comment by brainandforce** [comment]
Thanks for testing this so thoroughly; I'm interested in adapting what you're doing to improve the robustness of this package's testing suite.

**Comment by glwhart** [comment]
Years ago I wrote my own SNF/HNF routines in fortran but they were only for 3x3 cases. I suppose I could do that again, but it seems better to help someone else with a start get a code up to scratch so the whole community can use it...

Below is the code I use to generate a complete list of HNFs of a given determinant. I suspect it's pretty easy to follow. Feel free to use it to test. 


```
""" Generate all of the HNF matrices of determinant n """
function getAllHNFs(n)
# Even for n≈65 (>10,000 HNFs), this takes less than a second. No need for anything fancier.
    diags = tripletList(n) # All possible diagonal entries of HNF matrices with determinant n
    nHNF = sum([iD[2]*iD[3]^2 for iD ∈ diags]) # Number of HNF matrices to generate
    HNFs = zeros(Int,3,3,nHNF) # Preallocate array to store all HNFs
    iH = 1 # Counter for HNFs
    for iD ∈ diags # Loop over all possible diagonal entries
        for d1 ∈ 0:iD[2]-1 # Loop over row two off-diagonal entries
            for d2 ∈ 0:iD[3]-1 # Loop over row-three, column-1 entries
                for d3 ∈ 0:iD[3]-1 # Loop over row-three, column-2 entries
                    HNFs[:,:,iH] = [iD[1] 0 0; d1 iD[2] 0; d2 d3 iD[3]]
                    iH += 1 # Increment HNF counter
                end
            end
        end
    end
    return HNFs
end

""" Generate all integer triplets a*b*c = n """
function tripletList(n)
# Even for cases ≈ 100, this takes only a couple of μs. No need for anything fancier.
triples = Vector{Vector{Int64}}()
    # Loop over all triplets that a*b*c = n
    for i ∈ 1:n
        for j ∈ 1:n
            if i*j > n break end # Just for efficiency
            for k ∈ 1:n
                if i*j*k > n break end # Just for efficiency
                if i*j*k == n
                   push!(triples,[i,j,k])
                end
            end
        end
    end
    return triples
end
```

**Comment by brainandforce** [comment]
I've pushed a new version that should hopefully solve all of the outstanding issues. If there are other problems feel free to reopen the issue (or open a new one).

**Comment by glwhart** [comment]
I tested the SNF routine all HNFs up to determinant size 100 (about 670,000 matrices) and it seemed to work without a single error. Thanks!

```
begin
nH = 1
for j in 1:100
    test = getAllHNFs(j)
    safe = true
    println("j = ",j)
    for i in axes(test,3)
        s=NormalForms.snf(test[:,:,i])
        nH += 1
        if s.U*test[:,:,i]*s.V != s.S 
            println("************** Error")
            println("j = ",j," i = ",i)
            safe = false
            break
        end
    end
    if !safe
        break
    end
end
println("total HNFs: ",nH)
end
```
